config/routes.rb
Rails.application.routes.draw do
  resources :recipes

  resources :occasions

  resources :cuisines

  resources :ingredients

  root 'welcome#index'

  devise_for :users

  namespace :api, defaults:{ format: :json } do
    namespace :v1 do
      resources :cuisines, only: [:index, :create, :show, :update, :destroy]

      resources :occasions, only: [:index, :create, :show, :update, :destroy]

      post 'recipes/get_best_recipe'
      post 'recipes/get_fav_recipe'
      post 'recipes/save_rating'
      post 'recipes/save_review'
      get 'recipes/get_review/:id' => 'recipes#get_review'
      resources :recipes
    end
  end 

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	validates :recipe, presence: true
	validates :resipi, presence: true
	validates :cuisine_id, presence: true
	validates :instruction, presence: true
	validates :arahan, presence: true
	validates :time, presence: true
	validates :photo, presence: true
	validates :rating, presence: true

	has_and_belongs_to_many :occasions
	has_and_belongs_to_many :ingredients
	belongs_to :cuisine
	has_many :instructions
	has_many :comments

	def self.search(inputCuisine)
	  where("cuisine_id LIKE ?", "%#{inputCuisine}%") 
	end
end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < Api::V1::BaseController
  respond_to :json

  def index
    respond_with Recipe.all
  end

  def show
    recipe = Recipe.find(params[:id])

    render json: recipe.to_json(include: [:ingredients, :comments])
  end

  def get_best_recipe
    if (params[:cuisine] && params[:occasion].nil?)
      recipes = Recipe.joins(:cuisine).where("cuisines.cuisine IN (?)", params[:cuisine]).limit(params[:topRecipe])
    elsif (params[:cuisine].nil? && params[:occasion])
      recipes = Recipe.joins(:occasions).where("occasions.occasion IN (?)", params[:occasion]).limit(params[:topRecipe])
    elsif (params[:cuisine] && params[:occasion])
      recipes = Recipe.joins(:cuisine).joins(:occasions).where("cuisines.cuisine IN (?) AND occasions.occasion IN (?)", params[:cuisine], params[:occasion]).limit(params[:topRecipe])
    else
      recipes = Recipe.limit(params[:topRecipe])
    end
      
    render json: recipes.to_json(include: [:ingredients])
  end

  def get_fav_recipe
    recipes = Recipe.where("id IN (?)", params[:dataFavRecipe])

    render json: recipes.to_json(include: :ingredients)
  end

  def save_rating
    recipe = Recipe.find(params[:recipeId])
    recipe.rating = params[:rating]
    if recipe.save 
      render json: recipe, status: 201
    else
      render json: { errors: recipe.errors}, status: 422
    end
  end

  def save_review
    review = Review.new(params[:username, :comment, :recipe_id])

    if review.save 
      render json: review, status: 201
    else
      render json: { errors: review.errors}, status: 422
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  
  def new
  	@recipe = Recipe.new
  end

  def index
  	@recipes = Recipe.all
    if (params[:inputCuisine]=="")
      @recipes = Recipe.joins(:occasions).where(occasions: { id: params[:inputOccasion] })
    elsif (params[:inputOccasion]=="")
      @recipes = Recipe.where("cuisine_id = ?", "#{params[:inputCuisine]}")
    elsif (params[:inputCuisine]!=nil && params[:inputOccasion]!=nil)
      @recipes = Recipe.where("cuisine_id = ?", "#{params[:inputCuisine]}").joins(:occasions).where(occasions: { id: params[:inputOccasion] })
    end
  end

  def show
  	@recipe = Recipe.find(params[:id])
  end

  def edit
  	@recipe = Recipe.find(params[:id])
  end

  def create
  	@recipe = Recipe.new(permit_recipe)
  	if @recipe.save
  		flash[:success] = "Success!"
  		redirect_to recipes_path
  	else
  		render 'new'
  	end
  end

  def update
  	@recipe = Recipe.find(params[:id])

  	if @recipe.update(permit_recipe)
  		redirect_to recipes_path
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@recipe = Recipe.find(params[:id])
  	@recipe.destroy

  	redirect_to recipes_path
  end

  private
  	def permit_recipe
  		params.require(:recipe).permit(:recipe, :resipi, :cuisine_id, :instruction, :arahan, :time, :photo, :rating, occasion_ids:[], ingredient_ids:[])
  	end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<% if @recipe.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
    <%= pluralize(@recipe.errors.count, "error") %> prohibited
    this recipe from being saved:
  <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for @recipe, :html => {} do |f| %>
	<div class="form-group">
    <%= f.label :recipe, class: 'control-label' %>
    <%= f.text_field :recipe, class: 'form-control' %>    
  </div>
  <div class="form-group">
    <%= f.label :resipi, class: 'control-label' %>
    <%= f.text_field :resipi, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label "Cuisine", class: 'control-label' %>
    <%= f.collection_select(:cuisine_id, Cuisine.all, :id, :cuisine, {:prompt => "Choose cuisine"}, {:class => 'form-control'})%>
  </div>
  <div class="form-group">
    <%= f.label :instruction, class: 'control-label' %>
    <%= f.text_area :instruction, class: 'form-control' %>
  </div>

<% if false %>
  <%= f.fields_for @recipe.instructions.build do |p| %>
    <div class="controls">
      <div class="form-group">
        <%= p.label :instruction, class: 'control-label' %>
        <div class="entry form-group input-group">
          <%= p.text_field :instruction, class: 'form-control' %>
          <span class="input-group-btn">
            <button class="btn btn-success btn-add" type="button">
              <span class="fa fa-plus"></span>
            </button>
          </span>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

  <div class="form-group">
    <%= f.label :arahan, class: 'control-label' %>
    <%= f.text_area :arahan, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :time, class: 'control-label' %>
    <%= f.text_field :time, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :photo, class: 'control-label' %>
    <%= f.text_field :photo, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :rating, class: 'control-label' %>
    <%= f.text_field :rating, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label "Occasion", class: 'control-label' %>
      <%= f.collection_check_boxes :occasion_ids, Occasion.all, :id, :occasion do |b| %>
        <%= b.check_box %>
        <%= b.label %>
        <br>
      <% end %>
  </div>
  
  <div class="form-group">
    <%= f.label "Ingredient", class: 'control-label' %>
      <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :ingredient do |b| %>
        <%= b.check_box %>
        <%= b.label %>
      <% end %>
      <% if false %>
      <%= select_tag("recipe[ingredient_ids][]", options_for_select(Ingredient.all.collect { |ingredient| [ingredient.ingredient, ingredient.id] }, @recipe.ingredients.collect { |ingredient| ingredient.id}), {:multiple=>true, :size=>5, :class => 'form-control'}) %>
      <% end %>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to "Cancel", recipes_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="container">
	<div class="ordering-section-head text-center wow bounceInRight" data-wow-delay="0.4s">
		<h3>Edit Recipes</h3>
		<div class="dotted-line">
			<h4><%= link_to "Add recipe", new_recipe_path, class: 'btn btn-primary' %></h4>
		</div>
	</div>
    <div class="row">
        <div class="col-lg-12">
			<%= render 'form' %>
        </div>
    </div>
    <!-- /.row -->
</div>

app/views/recipes/index.html.erb
<div class="container">
	<div class="ordering-section-head text-center wow bounceInRight" data-wow-delay="0.4s">
		<h3>Manage Recipes</h3>
		<div class="dotted-line">
			<h4><%= link_to "Add recipe", new_recipe_path, class: 'btn btn-primary' %></h4>
		</div>
	</div>
	
	<table id="recipeTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
		<thead>
			<tr>
				<th>Photo</th>
				<th>Recipe</th>
				<th>Instruction</th>
				<th>Option</th>
			</tr>
		</thead>
		<tbody>
			<% @recipes.each do |x| %>
				<tr>
					<td><img src="<%= image_path(x.photo)%>" alt="" width="100px"></td>
					<td>
						Recipe: <%= x.recipe %> <br>
						Resipi: <%= x.resipi %> <br>
						<% @cuisine = Cuisine.find(x.cuisine_id) %>
						Cuisine: <%= @cuisine.cuisine %> <br>
						Time: <%= x.time %> <br>
						Rating: <%= x.rating %>
					</td>
					<td>
						Instruction: <%= x.instruction %> <br>
						Arahan: <%= x.arahan %>
					</td>
					<td>
						<%= link_to "Edit", edit_recipe_path(x), class: 'btn btn-primary' %>
						<%= link_to "Delete", recipe_path(x), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/recipes/new.html.erb
<div class="container">
	<div class="ordering-section-head text-center wow bounceInRight" data-wow-delay="0.4s">
		<h3>Add Recipes</h3>
		<div class="dotted-line">
			<h4><%= link_to "Add recipe", new_recipe_path, class: 'btn btn-primary' %></h4>
		</div>
	</div>
    <div class="row">
        <div class="col-lg-12">
			<%= render 'form' %>
        </div>
    </div>
    <!-- /.row -->
</div>

app/views/recipes/show.html.erb
<h1>Recipes#show</h1>
<p>Find me in app/views/recipes/show.html.erb</p>