config/routes.rb
Rails.application.routes.draw do
  resources :recipes

  resources :occasions

  resources :cuisines

  resources :ingredients

  root 'welcome#index'

  devise_for :users

  namespace :api, defaults:{ format: :json } do
    namespace :v1 do
      resources :cuisines, only: [:index, :create, :show, :update, :destroy]

      resources :occasions, only: [:index, :create, :show, :update, :destroy]

      post 'recipes/get_best_recipe'
      post 'recipes/get_fav_recipe'
      post 'recipes/save_rating'
      post 'recipes/save_review'
      get 'recipes/get_review/:id' => 'recipes#get_review'
      resources :recipes
    end
  end 

end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
	validates :cuisine, presence: true
	validates :masakan, presence: true

	has_many :recipes
end

app/controllers/api/v1/cuisines_controller.rb
class Api::V1::CuisinesController < Api::V1::BaseController
  respond_to :json

  def index
    respond_with Cuisine.all.reorder('cuisine')
  end

  def create
    cuisine = Cuisine.new(cuisine_params)

    if cuisine.save 
      render json: cuisine, status: 201
    else
      render json: { errors: cuisine.errors}, status: 422
    end
  end

  def show
    respond_with Cuisine.find(params[:id])
  end

  def update
    cuisine = Cuisine.find(params[:id])

    if cuisine.update(cuisine_params)
      render json: cuisine, status: 200
    else
      render json: { errors: cuisine.errors }, status: 422
    end
  end

  def destroy
    cuisine = Cuisine.find(params[:id])
    cuisine.destroy
    head 204
  end

  private
    def cuisine_params
      params.require(:cuisine).permit(:cuisine, :masakan) 
    end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  before_action :authenticate_user!
  
  def new
  	@cuisine = Cuisine.new
  end

  def index
  	@cuisines = Cuisine.all
  end

  def show
  	@cuisine = Cuisine.find(params[:id])
  end

  def edit
  	@cuisine = Cuisine.find(params[:id])
  end

  def create
  	@cuisine = Cuisine.new(permit_cuisine)
  	if @cuisine.save
  		flash[:success] = "Success!"
  		redirect_to cuisines_path
  	else
  		flash[:error] = @cuisine.errors.full_messages
  		redirect_to new_cuisine_path
  	end
  end

  def update
  	@cuisine = Cuisine.find(params[:id])

  	if @cuisine.update(permit_cuisine)
  		redirect_to @cuisine
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@cuisine = Cuisine.find(params[:id])
  	@cuisine.destroy

  	redirect_to cuisines_path
  end

  private
  	def permit_cuisine
  		params.require(:cuisine).permit(:cuisine, :masakan)
  	end
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/views/cuisines/_form.html.erb
<% if @cuisine.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@cuisine.errors.count, "error") %> prohibited
    this cuisine from being saved:
  </h2>
  <ul>
    <% @cuisine.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for @cuisine, :html => {:class => 'form-horizontal'} do |f| %>
  <div class="form-group">
    <%= f.label :cuisine, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :cuisine, class: 'form-control' %>
    </div>    
  </div>
  <div class="form-group">
    <%= f.label :masakan, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :masakan, class: 'form-control' %>
    </div>    
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to "Cancel", cuisines_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/cuisines/edit.html.erb
<div class="container">
	<div class="ordering-section-head text-center wow bounceInRight" data-wow-delay="0.4s">
		<h3>Edit Cuisines</h3>
		<div class="dotted-line">
			<h4><%= link_to "Add cuisine", new_cuisine_path, class: 'btn btn-primary' %></h4>
		</div>
	</div>
    <div class="row">
        <div class="col-lg-12">
			<%= render 'form' %>
        </div>
    </div>
    <!-- /.row -->
</div>

app/views/cuisines/index.html.erb
<div class="container">
	<div class="ordering-section-head text-center wow bounceInRight" data-wow-delay="0.4s">
		<h3>Manage Cuisines</h3>
		<div class="dotted-line">
			<h4><%= link_to "Add cuisine", new_cuisine_path, class: 'btn btn-primary' %></h4>
		</div>
	</div>
	
	<table id="cuisineTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
		<thead>
			<tr>
				<th>Cuisine</th>
				<th>Masakan</th>
				<th>Option</th>
			</tr>
		</thead>
		<tbody>
			<% @cuisines.each do |x| %>
				<tr>
					<td><%= x.cuisine %></td>
					<td><%= x.masakan %></td>
					<td>
						<%= link_to "Edit", edit_cuisine_path(x), class: 'btn btn-primary' %>
						<%= link_to "Delete", cuisine_path(x), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/cuisines/new.html.erb
<div class="container">
	<div class="ordering-section-head text-center wow bounceInRight" data-wow-delay="0.4s">
		<h3>Add Cuisines</h3>
		<div class="dotted-line">
			<h4><%= link_to "Add cuisine", new_cuisine_path, class: 'btn btn-primary' %></h4>
		</div>
	</div>
    <div class="row">
        <div class="col-lg-12">
			<%= render 'form' %>
        </div>
    </div>
    <!-- /.row -->
</div>

app/views/cuisines/show.html.erb
<h1>Cuisines#show</h1>
<p>Find me in app/views/cuisines/show.html.erb</p>

Cuisine: <%= @cuisine.cuisine %>
<br>
Masakan: <%= @cuisine.masakan %>