config/routes.rb
Rails.application.routes.draw do
  resources :recipes

  resources :occasions

  resources :cuisines

  resources :ingredients

  root 'welcome#index'

  devise_for :users

  namespace :api, defaults:{ format: :json } do
    namespace :v1 do
      resources :cuisines, only: [:index, :create, :show, :update, :destroy]

      resources :occasions, only: [:index, :create, :show, :update, :destroy]

      post 'recipes/get_best_recipe'
      post 'recipes/get_fav_recipe'
      post 'recipes/save_rating'
      post 'recipes/save_review'
      get 'recipes/get_review/:id' => 'recipes#get_review'
      resources :recipes
    end
  end 

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	validates :ingredient, presence: true
	validates :ramuan, presence: true

	has_and_belongs_to_many :recipes
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :authenticate_user!
  
  def new
  	@ingredient = Ingredient.new
  end

  def index
  	@ingredients = Ingredient.all
  end

  def show
  	@ingredient = Ingredient.find(params[:id])
  end

  def edit
  	@ingredient = Ingredient.find(params[:id])
  end

  def create
  	@ingredient = Ingredient.new(permit_ingredient)
  	if @ingredient.save
  		flash[:success] = "Success!"
  		redirect_to ingredients_path
  	else
  		flash[:error] = @ingredient.errors.full_messages
  		redirect_to new_ingredient_path
  	end
  end

  def update
  	@ingredient = Ingredient.find(params[:id])

  	if @ingredient.update(permit_ingredient)
  		redirect_to @ingredient
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@ingredient = Ingredient.find(params[:id])
  	@ingredient.destroy

  	redirect_to ingredients_path
  end

  private
  	def permit_ingredient
  		params.require(:ingredient).permit(:ingredient, :ramuan)
  	end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<% if @ingredient.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@ingredient.errors.count, "error") %> prohibited
    this ingredient from being saved:
  </h2>
  <ul>
    <% @ingredient.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for @ingredient, :html => {:class => 'form-horizontal'} do |f| %>
  <div class="form-group">
    <%= f.label :ingredient, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :ingredient, class: 'form-control' %>
    </div>    
  </div>
  <div class="form-group">
    <%= f.label :ramuan, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :ramuan, class: 'form-control' %>
    </div>    
  </div>
	<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to "Cancel", ingredients_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<div class="container">
	<div class="ordering-section-head text-center wow bounceInRight" data-wow-delay="0.4s">
		<h3>Edit Ingredients</h3>
		<div class="dotted-line">
			<h4><%= link_to "Add ingredient", new_ingredient_path, class: 'btn btn-primary' %></h4>
		</div>
	</div>
    <div class="row">
        <div class="col-lg-12">
			<%= render 'form' %>
        </div>
    </div>
    <!-- /.row -->
</div>

app/views/ingredients/index.html.erb
<div class="container">
	<div class="ordering-section-head text-center wow bounceInRight" data-wow-delay="0.4s">
		<h3>Manage Ingredients</h3>
		<div class="dotted-line">
			<h4><%= link_to "Add ingredient", new_ingredient_path, class: 'btn btn-primary' %></h4>
		</div>
	</div>
	
	<table id="ingredientTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
		<thead>
			<tr>
				<th>Ingredient</th>
				<th>Ramuan</th>
				<th>Option</th>
			</tr>
		</thead>
		<tbody>
			<% @ingredients.each do |x| %>
				<tr>
					<td><%= x.ingredient %></td>
					<td><%= x.ramuan %></td>
					<td>
						<%= link_to "Edit", edit_ingredient_path(x), class: 'btn btn-primary' %>
						<%= link_to "Delete", ingredient_path(x), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/ingredients/new.html.erb
<div class="container">
	<div class="ordering-section-head text-center wow bounceInRight" data-wow-delay="0.4s">
		<h3>Add Ingredients</h3>
		<div class="dotted-line">
			<h4><%= link_to "Add ingredient", new_ingredient_path, class: 'btn btn-primary' %></h4>
		</div>
	</div>
    <div class="row">
        <div class="col-lg-12">
			<%= render 'form' %>
        </div>
    </div>
    <!-- /.row -->
</div>

app/views/ingredients/show.html.erb
<h1>Ingredients#show</h1>
<p>Find me in app/views/ingredients/show.html.erb</p>

Ingredient: <%= @ingredient.ingredient %>
<br>
Ramuan: <%= @ingredient.ramuan %>