config/routes.rb
Rails.application.routes.draw do
  resources :recipes

  resources :occasions

  resources :cuisines

  resources :ingredients

  root 'welcome#index'

  devise_for :users

  namespace :api, defaults:{ format: :json } do
    namespace :v1 do
      resources :cuisines, only: [:index, :create, :show, :update, :destroy]

      resources :occasions, only: [:index, :create, :show, :update, :destroy]

      post 'recipes/get_best_recipe'
      post 'recipes/get_fav_recipe'
      post 'recipes/save_rating'
      post 'recipes/save_review'
      get 'recipes/get_review/:id' => 'recipes#get_review'
      resources :recipes
    end
  end 

end

app/models/occasion.rb
class Occasion < ActiveRecord::Base
	validates :occasion, presence: true
	validates :majlis, presence: true

	has_and_belongs_to_many :recipes
end

app/controllers/api/v1/occasions_controller.rb
class Api::V1::OccasionsController < Api::V1::BaseController
  respond_to :json

  def index
    respond_with Occasion.all.reorder('occasion')
  end

  def create
    occasion = Occasion.new(occasion_params)

    if occasion.save 
      render json: occasion, status: 201
    else
      render json: { errors: occasion.errors}, status: 422
    end
  end

  def show
    respond_with Occasion.find(params[:id])
  end

  def update
    occasion = Occasion.find(params[:id])

    if occasion.update(occasion_params)
      render json: occasion, status: 200
    else
      render json: { errors: occasion.errors }, status: 422
    end
  end

  def destroy
    occasion = Occasion.find(params[:id])
    occasion.destroy
    head 204
  end

  private
    def occasion_params
      params.require(:occasion).permit(:occasion, :majlis) 
    end
end

app/controllers/occasions_controller.rb
class OccasionsController < ApplicationController
  before_action :authenticate_user!
  
  def new
  	@occasion = Occasion.new
  end

  def index
  	@occasions = Occasion.all
  end

  def show
  	@occasion = Occasion.find(params[:id])
  end

  def edit
  	@occasion = Occasion.find(params[:id])
  end

  def create
  	@occasion = Occasion.new(permit_occasion)
  	if @occasion.save
  		flash[:success] = "Success!"
  		redirect_to occasions_path
  	else
  		flash[:error] = @occasion.errors.full_messages
  		redirect_to new_occasion_path
  	end
  end

  def update
  	@occasion = Occasion.find(params[:id])

  	if @occasion.update(permit_occasion)
  		redirect_to occasions_path
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@occasion = Occasion.find(params[:id])
  	@occasion.destroy

  	redirect_to occasions_path
  end

  private
  	def permit_occasion
  		params.require(:occasion).permit(:occasion, :majlis)
  	end
end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/views/occasions/_form.html.erb
<% if @occasion.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@occasion.errors.count, "error") %> prohibited
    this occasion from being saved:
  </h2>
  <ul>
    <% @occasion.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for @occasion, :html => {:class => 'form-horizontal'} do |f| %>
	<div class="form-group">
    <%= f.label :occasion, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :occasion, class: 'form-control' %>
    </div>    
  </div>
  <div class="form-group">
    <%= f.label :majlis, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :majlis, class: 'form-control' %>
    </div>    
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to "Cancel", occasions_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/occasions/edit.html.erb
<div class="container">
	<div class="ordering-section-head text-center wow bounceInRight" data-wow-delay="0.4s">
		<h3>Edit Occasions</h3>
		<div class="dotted-line">
			<h4><%= link_to "Add occasion", new_occasion_path, class: 'btn btn-primary' %></h4>
		</div>
	</div>
    <div class="row">
        <div class="col-lg-12">
			<%= render 'form' %>
        </div>
    </div>
    <!-- /.row -->
</div>

app/views/occasions/index.html.erb
<div class="container">
	<div class="ordering-section-head text-center wow bounceInRight" data-wow-delay="0.4s">
		<h3>Manage Occasions</h3>
		<div class="dotted-line">
			<h4><%= link_to "Add occasion", new_occasion_path, class: 'btn btn-primary' %></h4>
		</div>
	</div>
	
	<table id="occasionTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
		<thead>
			<tr>
				<th>Occasion</th>
				<th>Masakan</th>
				<th>Option</th>
			</tr>
		</thead>
		<tbody>
			<% @occasions.each do |x| %>
				<tr>
					<td><%= x.occasion %></td>
					<td><%= x.majlis %></td>
					<td>
						<%= link_to "Edit", edit_occasion_path(x), class: 'btn btn-primary' %>
						<%= link_to "Delete", occasion_path(x), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/occasions/new.html.erb
<div class="container">
	<div class="ordering-section-head text-center wow bounceInRight" data-wow-delay="0.4s">
		<h3>Add Occasions</h3>
		<div class="dotted-line">
			<h4><%= link_to "Add occasion", new_occasion_path, class: 'btn btn-primary' %></h4>
		</div>
	</div>
    <div class="row">
        <div class="col-lg-12">
			<%= render 'form' %>
        </div>
    </div>
    <!-- /.row -->
</div>

app/views/occasions/show.html.erb
<h1>Occasions#show</h1>
<p>Find me in app/views/occasions/show.html.erb</p>

Occasion: <%= @occasion.occasion %>
<br>
Majlis: <%= @occasion.majlis %>